<a href="https://colab.research.google.com/github/lakshitakaushik/portfolio/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [54]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import kurtosis, skew

In [55]:
df= pd.read_excel('/content/final dataset.xlsx')
df.head()

  Company name        Date  Open Price  Close Price
0     Axis Bank 2023-12-29     1106.75      1102.95
1     Axis Bank 2023-12-28     1109.85      1108.00
2     Axis Bank 2023-12-27     1093.95      1106.55
3     Axis Bank 2023-12-26     1089.05      1094.25
4     Axis Bank 2023-12-22     1097.95      1087.85

In [56]:
df['Date'] = pd.to_datetime(df['Date'])

In [57]:
df.columns

Index(['Company name ', 'Date', 'Open Price', 'Close Price'], dtype='object')

In [60]:
grouped_df = df.groupby('Company name ')

In [65]:
def kurtosis_value(series):
  return kurtosis(series)

def skewness_value(series):
  return skew(series)
descript=grouped_df['Open Price'].agg(['count','mean','std','min','max','var'])
print(descript)

                      count         mean         std      min      max  \
Company name
Axis Bank              4711   760.505010  348.095644   177.80  2037.00
Bandhan Bank           1427   362.660617  125.949653   163.95   727.00
Bank of Baroda         4711   341.016239  278.286488    36.30  1117.10
Bank of India          4711   190.517788  121.538678    31.00   580.00
Bank of Maharashtra    4711    35.038053   16.094488     8.35    94.90
CSB Bank               4053    70.782490   45.015252    10.35   245.40
Canara Bank            4711   296.564976  118.740852    76.60   836.00
Central Bank           4053    70.782490   45.015252    10.35   245.40
City Union Bank        4053    70.782490   45.015252    10.35   245.40
DCB Bank               8965    70.244930   51.833758     7.60   242.05
DHANLAXMI BANK          784    61.760765   17.616373    29.90   109.94
EQUITAS BANK             34    70.560882    6.900978    66.99   108.41
ESAF SFB BANK          4711   187.836143  126.833578    38.50   549.00
FEDERAL BANK           4711  1278.113914  525.129778   158.95  2564.00
HDFC BANK              4711   688.683698  330.043589   184.65  1774.00
ICICI BANK             4711    77.612074   35.220692    18.00  1005.05
IDBI BANK                 1    66.490000         NaN    66.49    66.49
IDFC BANK              4170   187.670513   82.615143    43.55   452.00
INDUSIND BANK             1  1615.000000         NaN  1615.00  1615.00
Indian Overseas bank   9421   368.718439  505.672770     6.60  2032.65
Jammu & Kashmir bank   4711   419.772893  432.154540    11.51  1899.00
Karnataka bank         4711   120.670197   44.609851    34.75   280.00
Karur Vysya bank       4710   290.888437  182.061099    20.35   849.10
Kotak Mahindra bank    4711   955.301337  518.832035   168.95  2204.90
Punjab & Sind bank     3222    42.841217   23.261094    10.35   146.10
Punjab National bank   4711   408.481036  362.345327    26.70  1380.00
RBL bank               1816   324.272412  175.764090    78.15   703.00
South Indian bank      4711    45.663696   48.065893     4.92   270.00
State bank of India    4711  1079.095033  852.637474   152.00  3515.00
Suryoday Small          684   146.660424   45.909250    78.10   293.00
TMB                     320   481.140625   49.492072   396.05   596.05
UCO Bank               4711    42.662868   27.934746     8.90   149.90
UTKARSHBNK              110    51.003455    2.574293    39.95    60.16
Ujjivan Small          1007    31.918024   11.902500    14.00    61.39
Union Bank             4711   143.872844   81.613672    22.90   420.00
Yes Bank               4578   325.682276  371.161069    10.79  1863.80

                                var
Company name
Axis Bank             121170.577637
Bandhan Bank           15863.315155
Bank of Baroda         77443.369542
Bank of India          14771.650148
Bank of Maharashtra      259.032543
CSB Bank                2026.372917
Canara Bank            14099.389856
Central Bank            2026.372917
City Union Bank         2026.372917
DCB Bank                2686.738518
DHANLAXMI BANK           310.336614
EQUITAS BANK              47.623493
ESAF SFB BANK          16086.756621
FEDERAL BANK          275761.284175
HDFC BANK             108928.770414
ICICI BANK              1240.497167
IDBI BANK                       NaN
IDFC BANK               6825.261823
INDUSIND BANK                   NaN
Indian Overseas bank  255704.950652
Jammu & Kashmir bank  186757.546651
Karnataka bank          1990.038835
Karur Vysya bank       33146.243840
Kotak Mahindra bank   269186.680591
Punjab & Sind bank       541.078474
Punjab National bank  131294.135944
RBL bank               30893.015338
South Indian bank       2310.330084
State bank of India   726990.661531
Suryoday Small          2107.659222
TMB                     2449.465194
UCO Bank                 780.350036
UTKARSHBNK                 6.626982
Ujjivan Small            141.669508
Union Bank              6660.791510
Yes Bank              137760.539309